#!/usr/bin/env bash
#Install and configure Nginx
sudo apt update -y
sudo apt install nginx -y
header_str=\
"
add_header X-Served-By $HOSTNAME;
"
sudo chown -R "$USER":"$USER" /etc/nginx/sites-available/default
echo "$header_str" > /etc/nginx/sites-available/default
sudo service nginx restart
