#!/usr/bin/env bash
# Installs HAProxy version 1.8 with the following configurations:
#+    Enables management via the init script.
#+    Distributes requests using a round-robin algorithm.

#apt-get install -y software-properties-common
#add-apt-repository -y ppa:vbernat/haproxy-1.8
apt update
apt install haproxy
#apt-get install -y haproxy=1.8.\*

#echo "ENABLED=1" >> /etc/default/haproxy

cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original
#touch /etc/haproxy/haproxy.cfg
add_conf=\
"
frontend my_frontend
    bind *:80
    default_backend my_servers

backend my_servers
    balance roundrobin
    server 5779-web-01 54.224.104.78:80 check
    server 5779-web-02 54.90.107.216:80 check
"
listen  hbnb
    bind 0.0.0.0:80
    mode http
    stats enable
    stats uri /haproxy?stats
    balance roundrobin
    option httpclose
    option forwardfor
    server 5779-web-01 54.147.175.242:80 check
    server 5779-web-02 54.242.59.215:80 check
"
echo $add_conf >> /etc/haproxy/haproxy.cfg

service haproxy restart
